
export const APPTODOADD = 'APPTODOADD';
export const APPTODODELETE = 'APPTODODELETE';
export const APPTODOFINISH = 'APPTODOFINISH';
export const APPTODOFINISHALL = 'APPTODOFINISHALL'; 
export const APPTODODELETEALL = 'APPTODODELETEALL'; 
export const APPTODOUNFINISHEDALL = 'APPTODOUNFINISHEDALL'; 

